"""Module 14: ReportLab-based PDF generation. Takes plain display-ready
values (already decrypted / already resolved to names by the caller) rather
than ORM objects, so this module has no knowledge of encryption or the data
layer — it only knows how to lay out a page."""
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

_STYLES = getSampleStyleSheet()
_TITLE = ParagraphStyle("MediShieldTitle", parent=_STYLES["Title"], textColor=colors.HexColor("#0f766e"))
_HEADING = ParagraphStyle("MediShieldHeading", parent=_STYLES["Heading2"], spaceBefore=12, spaceAfter=6)
_BODY = _STYLES["BodyText"]
_MUTED = ParagraphStyle("MediShieldMuted", parent=_STYLES["BodyText"], textColor=colors.grey, fontSize=9)


def _document() -> tuple[SimpleDocTemplate, BytesIO, list]:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=letter, topMargin=20 * mm, bottomMargin=20 * mm, leftMargin=20 * mm, rightMargin=20 * mm
    )
    return doc, buffer, []


def _header(story: list, subtitle: str) -> None:
    story.append(Paragraph("MediShield Hospital Management System", _TITLE))
    story.append(Paragraph(subtitle, _STYLES["Heading3"]))
    story.append(Spacer(1, 10))


def _patient_block(story: list, patient_name: str, extra: dict[str, str]) -> None:
    rows = [["Patient", patient_name]] + [[k, v] for k, v in extra.items()]
    table = Table(rows, colWidths=[100, 380])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 14))


def _footer(story: list, generated_at: str) -> None:
    story.append(Spacer(1, 20))
    story.append(Paragraph(
        "This document is generated by MediShield and is not a substitute for professional medical advice.",
        _MUTED,
    ))
    story.append(Paragraph(f"Generated: {generated_at}", _MUTED))


def build_medical_record_pdf(record: dict, patient_name: str, doctor_name: str, generated_at: str) -> bytes:
    doc, buffer, story = _document()
    _header(story, "Medical Record")
    _patient_block(
        story,
        patient_name,
        {
            "Doctor": doctor_name,
            "Record ID": str(record["id"]),
            "Date": record.get("created_at", ""),
            "Follow-up Date": record.get("follow_up_date") or "—",
        },
    )
    for label, key in [
        ("Symptoms", "symptoms"), ("Diagnosis", "diagnosis"),
        ("Treatment Plan", "treatment_plan"), ("Doctor Notes", "notes"),
    ]:
        story.append(Paragraph(label, _HEADING))
        story.append(Paragraph(record.get(key) or "—", _BODY))

    if record.get("ml_dengue_predicted") is not None:
        story.append(Paragraph("AI Screening Result", _HEADING))
        outcome = "Dengue Positive" if record["ml_dengue_predicted"] else "Dengue Negative"
        probability = record.get("ml_dengue_probability")
        confidence = f" ({probability * 100:.1f}% confidence)" if probability is not None else ""
        story.append(Paragraph(f"{outcome}{confidence}", _BODY))

    _footer(story, generated_at)
    doc.build(story)
    return buffer.getvalue()


def build_prescription_pdf(prescription: dict, patient_name: str, doctor_name: str, generated_at: str) -> bytes:
    doc, buffer, story = _document()
    _header(story, "Prescription")
    _patient_block(
        story,
        patient_name,
        {"Doctor": doctor_name, "Prescription ID": str(prescription["id"]), "Date": prescription.get("created_at", "")},
    )

    rows = [["Medicine", "Qty", "Dosage", "Frequency", "Duration", "Instructions"]]
    for item in prescription["items"]:
        rows.append([
            item.get("medicine_name") or "—", str(item.get("quantity") or "—"), item.get("dosage") or "—",
            item.get("frequency") or "—", item.get("duration") or "—", item.get("instructions") or "—",
        ])
    table = Table(rows, colWidths=[95, 35, 65, 75, 65, 125])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdfa")]),
            ]
        )
    )
    story.append(table)
    _footer(story, generated_at)
    doc.build(story)
    return buffer.getvalue()


def build_appointment_receipt_pdf(appointment: dict, patient_name: str, doctor_name: str, generated_at: str) -> bytes:
    doc, buffer, story = _document()
    _header(story, "Appointment Receipt")
    _patient_block(
        story,
        patient_name,
        {
            "Doctor": doctor_name,
            "Appointment ID": str(appointment["id"]),
            "Date & Time": appointment.get("appointment_date", ""),
            "Status": appointment["status"],
        },
    )
    story.append(Paragraph("Reason for Visit", _HEADING))
    story.append(Paragraph(appointment.get("reason") or "—", _BODY))

    _footer(story, generated_at)
    doc.build(story)
    return buffer.getvalue()


def build_lab_report_pdf(lab_test: dict, patient_name: str, generated_at: str) -> bytes:
    doc, buffer, story = _document()
    _header(story, "Lab Test Report")
    result = lab_test.get("result") or {}
    _patient_block(
        story,
        patient_name,
        {
            "Test": lab_test["test_name"],
            "Lab Test ID": str(lab_test["id"]),
            "Requested": lab_test.get("requested_at", ""),
            "Status": lab_test["status"],
        },
    )
    story.append(Paragraph("Result", _HEADING))
    story.append(Paragraph(result.get("result_value") or "Not yet available", _BODY))
    if result.get("completed_at"):
        story.append(Paragraph(f"Completed: {result['completed_at']}", _MUTED))

    _footer(story, generated_at)
    doc.build(story)
    return buffer.getvalue()
